name: Build Wheels

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    name: Linux (x86_64)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.21.3

      - name: Build wheels
        env:
          CIBW_PLATFORM: linux
        run: python -m cibuildwheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: wheelhouse/*.whl

  macos-arm:
    name: macOS (arm64)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew update
          brew install cairo eigen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.21.3

      - name: Build wheels
        env:
          CIBW_PLATFORM: macos
        run: python -m cibuildwheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-arm64
          path: wheelhouse/*.whl
